// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAmp2bKgvuwx70selS3rcWFIawpDM7w1M',
    appId: '1:16926826441:web:0e055e2206feba54211218',
    messagingSenderId: '16926826441',
    projectId: 'photoai-b405c',
    authDomain: 'photoai-b405c.firebaseapp.com',
    storageBucket: 'photoai-b405c.firebasestorage.app',
    measurementId: 'G-HBGCD76BPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJbcpbVEq755zzpu8cGUL2zKVIsht05yM',
    appId: '1:16046442525:android:ba82dddc2332e2fa0cdef4',
    messagingSenderId: '16046442525',
    projectId: 'nazar-d2761',
    storageBucket: 'nazar-d2761.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI9MQPXMU5rn8D_lzIE3qIQC-ZzQEN93o',
    appId: '1:16046442525:ios:6676ebad2cfa8e240cdef4',
    messagingSenderId: '16046442525',
    projectId: 'nazar-d2761',
    storageBucket: 'nazar-d2761.firebasestorage.app',
    iosClientId: '16046442525-d6toqc4i5omscec80bdp8qjdohblh5mt.apps.googleusercontent.com',
    iosBundleId: 'com.aedev.kisisel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-YEA7NDPzdMWw3ZKIMEfHuxmV-lGatKs',
    appId: '1:16926826441:ios:0ffb54a4d3815000211218',
    messagingSenderId: '16926826441',
    projectId: 'photoai-b405c',
    storageBucket: 'photoai-b405c.firebasestorage.app',
    iosBundleId: 'com.aedev.base',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAmp2bKgvuwx70selS3rcWFIawpDM7w1M',
    appId: '1:16926826441:web:eef1fa8ccc25e772211218',
    messagingSenderId: '16926826441',
    projectId: 'photoai-b405c',
    authDomain: 'photoai-b405c.firebaseapp.com',
    storageBucket: 'photoai-b405c.firebasestorage.app',
    measurementId: 'G-NTS30FSVGG',
  );
}